name: build-project

on:
  push:
    paths:
      - source/**
      - package/**
      - trigger_build.txt
  pull_request:
    paths:
      - trigger_build.txt

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        game:
          - l4d2
          #- l4d
          #- tf2
          
        os:
          #- windows-latest
          - ubuntu-latest
    env:
      METAMOD: ${{ github.workspace }}/metamod
      SOURCEMOD: ${{ github.workspace }}/sourcemod
      SDK: ${{ github.workspace }}/gamesdk
      
    steps:
        - uses: actions/checkout@v2
          with:
            ref: '${{matrix.game}}'
            path: actions-ext
            
        - name: Acquire SourceMod
          uses: actions/checkout@v2
          with:
              repository: alliedmodders/sourcemod
              submodules: recursive
              path: 'sourcemod'
              ref: '1.11-dev'
          
        - name: Acquire MetaMod:Source
          uses: actions/checkout@v2
          with:
              repository: alliedmodders/metamod-source
              path: 'metamod'
              ref: '1.11-dev'
        
        - name: Acquire SDK
          uses: actions/checkout@v2
          with:
              repository: alliedmodders/hl2sdk
              path: 'gamesdk'
              ref: '${{matrix.game}}'
          
        - name: Install Linux dependencies
          if: runner.os == 'Linux'
          run: |
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt install clang-10
            sudo apt-get install -y --install-recommends \
            gcc-multilib g++-multilib libstdc++6 lib32stdc++6 \
            libc6-dev libc6-dev-i386 linux-libc-dev \
            linux-libc-dev:i386 lib32z1-dev
            
        - name: Create Build Directory
          run: cmake -E make_directory ${{github.workspace}}/build
          
        - name: Configure CMake (Windows)
          working-directory: actions-ext
          if: runner.os == 'Windows'
          run: cmake -S . -B build -A Win32 --no-warn-unused-cli
              
        - name: Configure CMake (Linux)
          working-directory: actions-ext
          if: runner.os == 'Linux'
          run: cmake -S . -B build --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang
              
        - name: Build (Windows)
          working-directory: actions-ext
          if: runner.os == 'Windows'
          run: cmake --build build --config ${{env.BUILD_TYPE}} -j 6
           
        - name: Build (Linux)
          working-directory: actions-ext
          if: runner.os == 'Linux'
          run: cmake --build build -j 6
        
        - name: Copy output to package
          if: runner.os == 'Linux'
          working-directory: actions-ext
          run: cp ${{github.workspace}}/actions-ext/build/*.so ${{github.workspace}}/actions-ext/package/extensions/.

        - name: Copy output to package
          if: runner.os == 'Windows'
          working-directory: actions-ext
          run: copy ${{github.workspace}}/actions-ext/build/Release/*.dll ${{github.workspace}}/actions-ext/package/extensions/.

        - name: Upload output files
          uses: actions/upload-artifact@v2
          with:
            name: release-${{ matrix.os }}-${{ matrix.game }}
            path: ${{github.workspace}}/actions-ext/package/**
  
